library(shiny)
library(shinyjs)
library(SynTruthPkg)


ui <- fluidPage(
  useShinyjs(),
  fluidPage(
    # tags$div(class = "jumbotron text-center", style = "margin-bottom:0px;margin-top:0px",
    #          tags$h2(class = 'jumbotron-heading', stye = 'margin-bottom:0px;margin-top:0px', 
    #                  'SynTruth'),
    #          p('Synthetic data generator for assessing the performance of algorithms for predicting treatment response')
    # ),
    titlePanel(
      h1("SynTruth", align = 'center')),
    h3('Synthetic data generator for assessing the performance of algorithms for predicting treatment response', align = 'center'),
    br(),
    tags$div(
    tags$p("SynTruth generates synthetic datasets of"),
    tags$ol(
      tags$li('gene expression (marker, M and non-marker, NM genes)'),
      tags$li('patient benefit labels (benefit, B or non-benefit, NB)'),
      tags$li('treatment (0, 1-treatment of interest)'),
      tags$li('survival (time and event indicator)')
    ),
    tags$p("Each patient belongs to one of four groups: benefit and treatment 1 (B1); benefit and treatment 0 (B0); non-benefit and treatment 1 (NB1); non-benefit and treatment 0 (NB0)."),
    tags$p("The performance of machine learning algorithms can be assessed by comparing predictions to the ground truth generated by SynTruth."),
    ),
    sidebarLayout(
      sidebarPanel(
        h1("Gene expression"),
        fixedRow(
          column(4, 
                 numericInput('n_pts', "Number of patients", 50, min = 10, max = 2000),
                 numericInput('fraction_censored', "Fraction of censored patients", 0, min = 0, max = 1)
                 
          ),
          column(4,
                 numericInput('n_genes', HTML("Number of <br/> genes"), 100, min = 50, max = 20000),
                 numericInput('fraction_pts_benefit', "Fraction of B patients", 0.5, min = 0, max = 1)
                 
          ),
          column(4,
                 numericInput('fraction_tx_1', "Fraction of treatment1", 0.5, min = 0.2, max = 0.8),
                 numericInput('noisemean', HTML("Noise <br/> mean"), 0, min = -10,  max = 10),
                 numericInput('noisesd', HTML("Noise <br/> sd"), 0.2, min = 0,  max = 10)
          )
        ), 
        h3('Marker and nonmarker blocks'),
        fixedRow(
          column(8,
                 h3("M"),
                 textInput('marker_blocksizes', HTML("Marker blocksize"), "5,10"),
                 textInput('gene_effects', "Gene effects", "AND,OR"),
                 br(),
                 column(4, 
                        h4("NB"),
                        textInput('mus_NB', "Mu NB", "0,1"),
                        textInput('sds_NB', "SD NB", "0.4,0.5"),
                        textInput('rhos_NB', "Correlation NB", "0.8,0.7")
                 ),
                 column(4, 
                        h4("B"),
                        textInput('mu_diffs', "Mu diff", "4,2"),
                        textInput('sds_B', "SD B", "0.4,0.3"),
                        textInput('rhos_B', "Correlation B", "0.8,0.4"))
          ),
          column(4,
                 h3('NM'),
                 numericInput('mu_nonmarker', "Mu NM", 0, min = -5, max = 5),
                 textInput('sds_nonmarker', "SD NM", "0.4,0.3"),
                 textInput('rhos_nonmarker', "Correlation NM", "0.8,0.8")
          )
        ),
        h1("Survival"),
        fixedRow(
          column(6,
                 numericInput('HR_B0_NB0', "HR B0/NB0", 0.7, min = 0.1, max = 10),
                 numericInput('HR_NB1_NB0', "HR NB1/NB0", 0.9, min = 0, max = 10),
                 numericInput('HR_B1_NB0', "HR B1/NB0", 0.5, min = 0, max = 10)
          ),
          column(6,
                 numericInput('scale_NB0', "NB0 scale", 10, min = 0, max = 10),
                 numericInput('shape', "Weibull distribution shape", 1.4, min = -5, max = 5)
                 
          )
        ),
        fluidRow(
          actionButton("go", "GO", class = "btn-lg btn-success")
        )
      ),
      mainPanel(
        br(),
        h1("Results"),
        br(),
        #tableOutput('debug_print'),
        uiOutput("download"),
        br(),
        h1("Survival curves"),
        plotOutput("survplot"),
        #uiOutput("download_survplot"),
        #verbatimTextOutput("survplot_explain")
      )
    )
  )
)

server <- function(input, output, session){
  
  
  observeEvent(input$go, {
    #output$debug_print <- renderTable(gep())
    #output$debug_print <- renderPrint(input_list())
    #output$debug_print <- renderPrint(syndata())
    
    parsed_num_vec_inputs <- reactive({
      x <- list(marker_blocksizes = input$marker_blocksizes, mus_NB = input$mus_NB, sds_NB = input$sds_NB, 
                rhos_NB = input$rhos_NB, mu_diffs = input$mu_diffs, sds_B = input$sds_B, 
                rhos_B = input$rhos_B, sds_nonmarker = input$sds_nonmarker, 
                rhos_nonmarker = input$rhos_nonmarker)
      for (i in 1:length(x)){
        x[[i]] <- as.numeric(unlist(strsplit(x[[i]], ",")))
      }
      x
    })
    
    
    parsed_char_vec_input <- reactive({
      list(gene_effects = unlist(strsplit(input$gene_effects, ",")))
    })
    
    input_list <- reactive({
      parsed_inputs <- c(names(parsed_num_vec_inputs()), 'gene_effects')
      non_parsed_input_names <- setdiff(names(input), parsed_inputs)
      non_parsed_input <- reactiveValuesToList(input)[non_parsed_input_names]
      as.list(c(parsed_num_vec_inputs(), parsed_char_vec_input(), non_parsed_input))
    })
    
    
    syndata <- reactive({
      SynTruthPkg::get_best_gep(params = input_list(), n_repeats = 100, threshold = 0.05)
    })
    
    gep <- reactive(syndata()$best_gep)
    
    output_hrs <- reactive(syndata()$best_output_hs)
    
    
    # output$download_survplot <- renderUI({
    #   downloadButton('download_survplot', "Download survival plot" )
    # })
    
    output$survplot <- renderPlot({
      SynTruthPkg::plot_surv_curve(gep = gep(), output_hrs = output_hrs(), 
                                   mytitle = "Survival plot")
    })
    
    output$download <- renderUI({
      downloadButton('download_data', "Download synthetic data" )
    })
  })
  

  
  output$download_data <- downloadHandler(
    filename = function() {
      "synthetic_data.txt"
    },
    content = function(file) {
      write.csv(gep(), file, row.names = F, sep = "\t")
    }
  )
  
  
}

shinyApp(ui, server)
